version: 2
jobs:
  build:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/fitlins
    steps:
      - run:
          name: Install parallel gzip and Python 3
          command: |
            apk add --no-cache pigz python3
      - checkout
      - setup_remote_docker
      - run:
          name: Fetch latest release image
          no_output_timeout: 10m
          command: |
            docker pull poldracklab/fitlins:latest
      - run:
          name: Build image
          no_output_timeout: 30m
          command: |
            THISVERSION=$( python3 -c 'import fitlins; print(fitlins.__version__)' )
            if [[ ${THISVERSION:0:1} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            docker build \
              --tag poldracklab/fitlins:latest \
              --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
              --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" .
      - run:
          name: Verify executable can be run
          command: docker run --rm -it poldracklab/fitlins:latest --help
      - run:
          name: Check version
          command: |
              docker run --rm -it poldracklab/fitlins:latest --version
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save poldracklab/fitlins:latest \
            | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz
            - src/fitlins

  deploy_test:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              zcat /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
            fi
      - run:
          name: Deploy to PyPi
          command: |
            pip install "setuptools>=27.0" twine
            echo "${CIRCLE_TAG}" > fitlins/VERSION
            python setup.py sdist

  deploy_master:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              zcat /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag poldracklab/fitlins poldracklab/fitlins:master
              docker push poldracklab/fitlins:master
            fi

  deploy:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              zcat /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push poldracklab/fitlins:latest
              docker tag poldracklab/fitlins poldracklab/fitlins:$CIRCLE_TAG
              docker push poldracklab/fitlins:$CIRCLE_TAG
            fi
      - run:
          name: Deploy to PyPi
          command: |
            pip install "setuptools>=27.0" twine
            echo "${CIRCLE_TAG}" > fitlins/VERSION
            python setup.py sdist
            twine upload dist/*

workflows:
  version: 2
  fitlins_tests:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_test:
          requires:
            - build
          filters:
            branches:
              only: /rel\/[\d\.]+/
            tags:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
